# Generated by Django 6.0.6 on 2026-07-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mike & Sarah' or 'Grandma & Grandpa'", max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='reservations.family')),
            ],
            options={
                'ordering': ['family__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Optional: the household this person belongs to, for grouping on the request form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='reservations.household'),
        ),
    ]
