# Generated by Django 5.2.16 on 2026-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_preference',
            field=models.CharField(choices=[('own_family', 'Only requests from my own family'), ('all', 'All requests, from any family'), ('none', "Don't email me about requests")], default='own_family', help_text="Which new-request emails you'd like to receive, if you're an approver.", max_length=20),
        ),
    ]
