# Generated by Django 5.2.16 on 2026-07-10 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('lost_and_found', 'Lost & Found')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Lost & Found only: whether the item has been picked up by its owner.'),
        ),
    ]
