# Generated by Django 5.2.15 on 2026-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
