# Generated by Django 5.2.16 on 2026-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistrun_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unchecked when an item is deleted. Kept around (rather than hard-deleted) so completed checklist runs that already checked it off keep showing it in their history.'),
        ),
    ]
